#!/usr/bin/env python

import sys
sys.path.insert(1, '/usr/local/lib/python2.7/site-packages')

from hello.application import Application

if __name__ == "__main__":
    app = Application(package="hello-world", version="0.3")
    app.run()
