#!/usr/bin/env python

import sys
sys.path.insert(1, '/usr/local/lib/python2.7/site-packages')

from hello.application import Application

if __name__ == "__main__":
    try:
        app = Application(package="hello-world", 
                          version="0.4",
                          pkgdatadir="/usr/local/share/hello-world")
    except Exception, e:
        sys.exit("Could not initialize application: %s" % str(e))
    app.run()
